export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";
export const GET_ERRORS = "GET_ERRORS";

export const CREATE_USER_POST = "CREATE_USER_POST";
export const POST_SUCCESS = "POST_SUCCESS";

export const CREATE_USER_COMMENT_START = "CREATE_USER_COMMENT_START";
export const CREATE_USER_COMMENT_SUCCESS = "CREATE_USER_COMMENT_SUCCESS";

export const FETCH_PUBLIC_USERS_START = "FETCH_PUBLIC_USERS_START";
export const FETCH_PUBLIC_USERS_SUCCESS = "FETCH_PUBLIC_USERS_SUCCESS";
export const FETCH_PUBLIC_USERS_FAIL = "FETCH_PUBLIC_USERS_FAIL";

export const FETCH_PRIVATE_IMAGES_START = "FETCH_PRIVATE_IMAGES_START";
export const FETCH_PRIVATE_IMAGES_SUCCESS = "FETCH_PRIVATE_IMAGES_SUCCESS";
export const FETCH_PRIVATE_IMAGES_FAIL = "FETCH_PRIVATE_IMAGES_FAIL";

export const FETCH_PRIVATE_VIDEOS_START = "FETCH_PRIVATE_VIDEOS_START";
export const FETCH_PRIVATE_VIDEOS_SUCCESS = "FETCH_PRIVATE_VIDEOS_SUCCESS";
export const FETCH_PRIVATE_VIDEOS_FAIL = "FETCH_PRIVATE_VIDEOS_FAIL";

export const FETCH_POST_LOVES_START = "FETCH_POST_LOVES_START";
export const FETCH_POST_LOVES_SUCCESS = "FETCH_POST_LOVES_SUCCESS";
export const FETCH_POST_LOVES_FAIL = "FETCH_POST_LOVES_FAIL";

export const FETCH_COMMENTS_POST_START = "FETCH_COMMENTS_POST_START";
export const FETCH_COMMENTS_POST_SUCCESS = "FETCH_COMMENTS_POST_SUCCESS";
export const FETCH_COMMENTS_POST_FAIL = "FETCH_COMMENTS_POST_FAIL";

export const FETCH_WHOAMI_START = "FETCH_WHOAMI_START";
export const FETCH_WHOAMI_SUCCESS = "FETCH_WHOAMI_SUCCESS";
export const FETCH_WHOAMI_FAIL = "FETCH_WHOAMI_FAIL";
export const FETCH_WHOAMI_NULL = "FETCH_WHOAMI_NULL";
export const PUT_WHOAMI = "PUT_WHOAMI";

export const FETCH_SUGGESTED_USERS_START = "FETCH_SUGGESTED_USERS_START";
export const FETCH_SUGGESTED_USERS_SUCCESS = "FETCH_SUGGESTED_USERS_SUCCESS";
export const FETCH_SUGGESTED_USERS_FAIL = "FETCH_SUGGESTED_USERS_FAIL";

export const FETCH_POST_DETAILS_START = "FETCH_POST_DETAILS_START";
export const FETCH_POST_DETAILS_SUCCESS = "FETCH_POST_DETAILS_SUCCESS";
export const FETCH_POST_DETAILS_FAIL = "FETCH_POST_DETAILS_FAIL";

export const WEB_INFO_FOOTER_SIDEBAR = "WEB_INFO_FOOTER_SIDEBAR";
