export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";
export const GET_ERRORS = "GET_ERRORS";

export const SET_USER_POST = "SET_USER_POST";

export const FETCH_PUBLIC_USERS_START = "FETCH_PUBLIC_USERS_START";
export const FETCH_PUBLIC_USERS_SUCCESS = "FETCH_PUBLIC_USERS_SUCCESS";
export const FETCH_PUBLIC_USERS_FAIL = "FETCH_PUBLIC_USERS_FAIL";

export const FETCH_WHOAMI_START = "FETCH_WHOAMI_START";
export const FETCH_WHOAMI_SUCCESS = "FETCH_WHOAMI_SUCCESS";
export const FETCH_WHOAMI_FAIL = "FETCH_WHOAMI_FAIL";
export const FETCH_WHOAMI_NULL = "FETCH_WHOAMI_NULL";
export const PUT_WHOAMI = "PUT_WHOAMI";

export const FETCH_SUGGESTED_USERS_START = "FETCH_SUGGESTED_USERS_START";
export const FETCH_SUGGESTED_USERS_SUCCESS = "FETCH_SUGGESTED_USERS_SUCCESS";
export const FETCH_SUGGESTED_USERS_FAIL = "FETCH_SUGGESTED_USERS_FAIL";

export const WEB_INFO_FOOTER_SIDEBAR = "WEB_INFO_FOOTER_SIDEBAR";
