export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const FETCH_SUGGESTED_USERS_START = "FETCH_SUGGESTED_USERS_START";
export const FETCH_SUGGESTED_USERS_SUCCESS = "FETCH_SUGGESTED_USERS_SUCCESS";
export const FETCH_SUGGESTED_USERS_FAIL = "FETCH_SUGGESTED_USERS_FAIL";
